[build]
  command = "npm run build"
  publish = "dist"


# Config for the Netlify Build Plugin: netlify-plugin-form-submissions
[[plugins]]
  package = "netlify-plugin-form-submissions"

  [plugins.inputs]
    # Get submissions for specific forms
    # e.g. "form-name"
    # e.g. ["form-name-1", "form-name-2"]
    # e.g. "ALL"
    # default: "ALL"
    formNames = "ALL"

    # the folder to recieve json files for each form
    dataDirectory = "src/_data"



